// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.cairn.rmi.server;

public final class TaskManagerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements com.cairn.rmi.TaskManagerInterface
{
    private static final long serialVersionUID = 2;
    
    private static final java.lang.reflect.Method $method_submitTask_0;
    private static final java.lang.reflect.Method $method_submitTask_1;
    
    static {
	try {
	    $method_submitTask_0 = com.cairn.rmi.TaskManagerInterface.class.getMethod("submitTask", new java.lang.Class[] {com.cairn.rmi.TaskInterface.class, java.lang.Object.class});
	    $method_submitTask_1 = com.cairn.rmi.TaskManagerInterface.class.getMethod("submitTask", new java.lang.Class[] {java.lang.String.class, java.lang.Object.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public TaskManagerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of submitTask(TaskInterface, Object)
    public java.lang.Object submitTask(com.cairn.rmi.TaskInterface $param_TaskInterface_1, java.lang.Object $param_Object_2)
	throws com.cairn.rmi.TaskException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_submitTask_0, new java.lang.Object[] {$param_TaskInterface_1, $param_Object_2}, 2598995844536982295L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.cairn.rmi.TaskException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of submitTask(String, Object)
    public java.lang.Object submitTask(java.lang.String $param_String_1, java.lang.Object $param_Object_2)
	throws com.cairn.rmi.TaskException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_submitTask_1, new java.lang.Object[] {$param_String_1, $param_Object_2}, -2007632421700228321L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.cairn.rmi.TaskException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
